# 心跳握手时间
heartbeat = 60
# 最大包的大小，128K
frame_max = 131072
# channle
channel_max = 1024
# 内存占到40%则开始流控机制
vm_memory_high_watermark.relative = 0.4

log.console = false
log.console.level = info
log.exchange = false
log.exchange.level = info

ssl_options.cacertfile           = /etc/rabbitmq/certs/ca.crt
ssl_options.certfile             = /etc/rabbitmq/certs/server.crt
ssl_options.keyfile              = /etc/rabbitmq/certs/server.key
ssl_options.verify               = verify_peer
ssl_options.fail_if_no_peer_cert = true

mqtt.listeners.ssl.default=8883
mqtt.listeners.tcp.default=1883

