#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M

kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.native.ignoreDisabledTargets=true

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true